[phases.setup]
nixPkgs = ["python311", "postgresql", "pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn flairies_backend.wsgi --bind 0.0.0.0:$PORT"
